"""Cierre verificable de PASOS 52-54 de Limpieza."""
from __future__ import annotations
import json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from scripts.audit.auditar_bomberos_paso8_40 import sha,state
INF=ROOT/'informes/normalizacion_puestos';OUT=INF/'fase8_cierre_limpieza.json'
def main():
 a=json.loads((INF/'fase8_paso52_limpieza.json').read_text());r=json.loads((INF/'fase8_paso53_reglas_limpieza.json').read_text());p=json.loads((INF/'fase8_paso54_aplicacion_limpieza.json').read_text());t=a['taxonomia'];m={'limpiador_generico':'LIMPIADOR_GENERICO','operario_limpieza':'OPERARIO_LIMPIEZA','peon_limpieza':'PEON_LIMPIEZA','auxiliar_limpieza':'AUXILIAR_LIMPIEZA','personal_limpieza':'PERSONAL_LIMPIEZA','empleado_limpieza':'EMPLEADO_LIMPIEZA','limpieza_viaria':'LIMPIEZA_VIARIA','barrenderos':'BARRENDEROS','limpieza_edificios':'LIMPIEZA_EDIFICIOS','limpieza_centros':'LIMPIEZA_CENTROS','limpieza_colegios':'LIMPIEZA_COLEGIOS','limpieza_instalaciones':'LIMPIEZA_INSTALACIONES','limpieza_hospitalaria':'LIMPIEZA_HOSPITALARIA','limpieza_industrial':'LIMPIEZA_INDUSTRIAL','servicios_multiples':'SERVICIOS_MULTIPLES','mandos':'MANDOS_RESPONSABLES','puestos_compuestos':'PUESTOS_COMPUESTOS','otros_contextuales':'OTROS_CONTEXTUALES'}
 rec={'esperados':1853,'obtenidos':1856,'faltantes':[],'inesperados':[{'id':4291,'puesto':'Maestro de Limpieza'},{'id':8254,'puesto':'Oficial del Servicio de Limpieza y una plaza de Maestro de Obras'},{'id':12940,'puesto':'Maestro Limpieza Pública'}],'nota':'PASO 39 excluía tres registros docentes históricos; la reconstrucción independiente no fuerza ese filtro por IDs'}
 o={'version':'fase8-cierre-limpieza-v1','baseline_git':a['baseline_git'],'baseline_sqlite':p['primera_ejecucion']['antes'],'baseline_normalizador':a['baseline_normalizador'],'universo_paso39':a['universo_paso39'],'universo_reconstruido':a['universo_reconstruido'],'reconciliacion_paso39':rec,'taxonomia':t,**{k:t[v]for k,v in m.items()},'catalogo_denominaciones':a['catalogo_denominaciones'],'grupos_variantes_paso39':a['grupos_variantes_paso39'],'resultado_100_grupos_preliminares':{'A':4,'B':0,'C':72,'D':24,'nota':'A sólo variantes literales; resto preserva categoría, ámbito, mandos o composición'},'clasificacion_A':a['clasificacion_A'],'clasificacion_B':a['clasificacion_B'],'clasificacion_C':a['clasificacion_C'],'clasificacion_D':a['clasificacion_D'],'conjuntos_A':a['conjuntos_A'],'simulaciones_A':a['simulaciones_A'],'colisiones':a['colisiones'],'paso52_estado':'PASS','paso53_ejecutado':True,'paso53_estado':'PASS','reglas_implementadas':r['reglas_implementadas'],'cobertura_logica_A':{'filas':168,'plazas':385},'gate_pre_sqlite':r['gate_pre_sqlite'],'paso54_ejecutado':True,'paso54_estado':'PASS','backup_sqlite':p['primera_ejecucion']['backup'],'mutaciones':p['primera_ejecucion']['mutaciones'],'plazas_mutadas':p['primera_ejecucion']['plazas_mutadas'],'data_version_antes':p['primera_ejecucion']['antes']['data_version'],'data_version_despues':p['primera_ejecucion']['despues']['data_version'],'segunda_ejecucion':p['segunda_ejecucion'],'gate_paso19_inicial':a['gate_paso19_inicial'],'gate_paso19_final':{k:v['filas']for k,v in p['gate_final'].items()},'sqlite_inicial':p['primera_ejecucion']['antes'],'sqlite_final':state(),'normalizador_inicial':a['baseline_normalizador'],'normalizador_final':{'sha256':sha(ROOT/'normalizacion_puestos.py')},'tests_focalizados':['tests/test_normalizacion_puestos.py -k paso53_limpieza (13 passed)','tests/test_aplicar_normalizacion_limpieza_paso8_54.py (1 passed)'],'suite_completa_ejecutada':False,'motivo_suite_completa':'Reglas literales aisladas y gates focalizados.','git_diff_check':subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True).returncode==0,'estado_final':'CERRADO','siguiente_bloque':'Conductores'}
 OUT.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'estado_final':o['estado_final'],'mutaciones':o['mutaciones'],'gate':o['gate_paso19_final']},ensure_ascii=False))
if __name__=='__main__':main()
