"""Compone el cierre verificable de PASOS 40-42 de Bomberos."""
from __future__ import annotations
import hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from scripts.audit.auditar_bomberos_paso8_40 import auditar, state, sha, ROOT, DB
from scripts.audit.auditar_criterio_dry_run_global_paso8_19 import auditar as gate_auditar
INF=ROOT/'informes/normalizacion_puestos';OUT=INF/'fase8_cierre_bomberos.json'
def main():
 a=auditar();pre=json.loads((INF/'fase8_paso40_bomberos.json').read_text());app=json.loads((INF/'fase8_paso42_aplicacion_bomberos.json').read_text());g=gate_auditar(DB);s=state();n=sha(ROOT/'normalizacion_puestos.py')
 r={'version':'fase8-cierre-bomberos-v1','baseline_git':pre['baseline_git'],'baseline_sqlite':app['primera_ejecucion']['antes'],'baseline_normalizador':pre['baseline_normalizador'],'universo_paso39':a['universo_paso39'],'universo_reconstruido':a['universo_reconstruido'],'reconciliacion_paso39':a['reconciliacion_paso39'],'taxonomia':a['taxonomia'],'catalogo_denominaciones':a['catalogo_denominaciones'],'grupos_variantes_paso39':a['grupos_variantes_paso39'],'bombero_base':a['bombero_base'],'bombero_conductor':a['bombero_conductor'],'mandos_rangos':a['mandos_rangos'],'puestos_compuestos':a['puestos_compuestos'],'otras_especialidades':a['otras_especialidades'],'ambiguos':a['ambiguos'],'clasificacion_A':a['clasificacion_A'],'clasificacion_B':a['clasificacion_B'],'clasificacion_C':a['clasificacion_C'],'clasificacion_D':a['clasificacion_D'],'conjuntos_A':a['conjuntos_A'],'simulaciones_A':a['simulaciones_A'],'colisiones':a['colisiones'],'paso40_estado':'COMPLETADO','paso41_ejecutado':True,'paso41_estado':'PASS','reglas_implementadas':['Bombero: bombero/bombero-a','Bombero-Conductor: variantes completas de espacio, guion y género'],'gate_pre_sqlite':app['primera_ejecucion']['gate_previo'],'paso42_ejecutado':True,'paso42_estado':'PASS','backup_sqlite':app['primera_ejecucion']['backup'],'mutaciones':app['primera_ejecucion']['mutaciones'],'data_version_antes':app['primera_ejecucion']['antes']['data_version'],'data_version_despues':app['primera_ejecucion']['despues']['data_version'],'segunda_ejecucion':app['segunda_ejecucion'],'gate_paso19_inicial':pre['gate_paso19_inicial'],'gate_paso19_final':{'cambios_reales_recalculables':g['cambios_reales_recalculables']['filas'],'discrepancias_contextuales_no_recalculables':g['discrepancias_contextuales_no_recalculables']['filas'],'discrepancias_no_clasificables_automaticamente':g['discrepancias_no_clasificables_automaticamente']['filas']},'sqlite_inicial':app['primera_ejecucion']['antes'],'sqlite_final':s,'normalizador_inicial':pre['baseline_normalizador'],'normalizador_final':{'sha256':n},'tests_focalizados':['tests/test_auditar_bomberos_paso8_40.py (3 passed)','tests/test_aplicar_normalizacion_bomberos_paso8_42.py (1 passed)','tests/test_auditar_criterio_dry_run_global_paso8_19.py (3 passed)','tests/test_normalizacion_puestos.py -k paso41_bomberos or fotocomposicion (13 passed)'],'suite_completa_ejecutada':False,'motivo_suite_completa':'No necesaria; cambio focalizado y gates aislados','git_diff_check':subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True).returncode==0,'estado_final':'CERRADO','siguiente_bloque':'Bibliotecas y archivos'}
 OUT.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'estado_final':r['estado_final'],'mutaciones':r['mutaciones'],'gate':r['gate_paso19_final']},ensure_ascii=False))
if __name__=='__main__':main()
